name: WobbleTeams
version: 2.5.0
main: net.wobble.teams.WobbleTeams
api-version: '1.21'
author: Wobble

softdepend:
  - PlaceholderAPI

commands:
  team:
  teamsettings:
  allygui:

permissions:
  wobbleteams.admin:
    default: op
