name: WTeams
version: 2.5.0

main: net.wobble.wteams.WTeams

api-version: '1.21'

author: Wobble



softdepend:

  - PlaceholderAPI



commands:

  team:

    description: Main team command

    usage: /team

  teamsettings:

    description: Open team settings

    usage: /teamsettings

  allygui:

    description: Open ally manager GUI

    usage: /allygui



permissions:

  wteams.admin:

    description: Full admin access to WTeams

    default: op

  wteams.reload:

    description: Reload WTeams

    default: op

  wteams.rename:

    description: Allow renaming teams

    default: op

