name: KTeams
version: 2.5.0

main: net.klouse.kteams.KTeams

api-version: '1.21'

author: Klouse



softdepend:

  - PlaceholderAPI



commands:

  team:

    description: Main team command

    usage: /team

  teamsettings:

    description: Open team settings

    usage: /teamsettings

  allygui:

    description: Open ally manager GUI

    usage: /allygui



permissions:

  kteams.admin:

    description: Full admin access to KTeams

    default: op

  kteams.reload:

    description: Reload KTeams

    default: op

  kteams.rename:

    description: Allow renaming teams

    default: op

